export const shopItemsData = [
  {
    id: 1,
    productTitle: "Casual Shirt",
    price: 4500,
    desc: "Denim Shirts | Custom Fit, Garment Washed...",
    img: "public/images/Casual-shirt.jpg",
  },
  {
    id: 2,
    productTitle: "Office Shirt",
    price: 10000,
    desc: "Solid Men Shirt Male Clothing Slim Fit Oxford Cotton Short Sleeve Casual Shirts.",
    img: "public/images/office-shirt.jpg",
  },
  {
    id: 3,
    productTitle: "T Shirt",
    price: 2500,
    desc: "Custom T-shirts: Design & Print Your Own Shirt Online..",
    img: "public/images/T-shirt.jpg",
  },
  {
    id: 4,
    productTitle: "Mens Suit",
    price: 30000,
    desc: "Bespoke Business Suits, Tailored to Last..",
    img: "public/images/Mens-Suit.jpg",
  },
  {
    id: 5,
    productTitle: "Mens Long Sleeve ",
    price: 6750,
    desc: "Fashion Mens Long Sleeve Casual Pattern Floral Polo Business Printed...",
    img: "public/images/Mens-Long-Sleeve.jpg",
  },
  {
    id: 6,
    productTitle: "Plain Unisex T-shirts",
    price: 6500,
    desc: "Cool and suitable for that classy casual look. You can wear this with jeans/chinos and sneakers.",
    img: "public/images/Plain-Unisex-T-shirts.jpg",
  },
  {
    id: 7,
    productTitle: "Embroidered Polo T-shirts",
    price: 6000,
    desc: "Legend of zelda make it rain' Men's Pique Polo Shirt | Spreadshirt.",
    img: "public/images/Embroidered-Polo-T-shirts.jpg",
  },
  {
    id: 8,
    productTitle: "Fashion Mens Vintage ",
    price: 4905,
    desc: "Fashion Mens Vintage Patterned Casual Short Sleeve Beach Shirts",
    img: "public/images/Fashion-Mens-Vintage.jpg",
  },
];
